//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4範本
{
    using System;
    using System.Collections.Generic;
    using Model;
    using System.ComponentModel;
    
    public class UnitbaViewModel : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(string propertyname)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyname));
            }
        }
    	private  UnitbaModel unitbaModel {get;set;}
    	public  UnitbaViewModel()
    	{
    		unitbaModel = new UnitbaModel();
        	單位  = "";
        	說明  = "";
        	輸入人員  = "";
        	輸入地點  = "";
        	增刪修  = "";
        	選擇  = "";
    	}
        public string 單位 { get{ if (unitbaModel.單位==null) {unitbaModel.單位="";}  return unitbaModel.單位 ;} set{unitbaModel.單位 = value; 	OnPropertyChanged("單位");} }
        public string 說明 { get{ if (unitbaModel.說明==null) {unitbaModel.說明="";}  return unitbaModel.說明 ;} set{unitbaModel.說明 = value; 	OnPropertyChanged("說明");} }
        public byte 小數位數 { get{return unitbaModel.小數位數 ;} set{unitbaModel.小數位數 = value;	OnPropertyChanged("小數位數"); } }
        public System.DateTime 輸入日期 { get{return unitbaModel.輸入日期 ;} set{unitbaModel.輸入日期 = value;	OnPropertyChanged("輸入日期"); } }
        public string 輸入人員 { get{ if (unitbaModel.輸入人員==null) {unitbaModel.輸入人員="";}  return unitbaModel.輸入人員 ;} set{unitbaModel.輸入人員 = value; 	OnPropertyChanged("輸入人員");} }
        public string 輸入地點 { get{ if (unitbaModel.輸入地點==null) {unitbaModel.輸入地點="";}  return unitbaModel.輸入地點 ;} set{unitbaModel.輸入地點 = value; 	OnPropertyChanged("輸入地點");} }
        public string 增刪修 { get{ if (unitbaModel.增刪修==null) {unitbaModel.增刪修="";}  return unitbaModel.增刪修 ;} set{unitbaModel.增刪修 = value; 	OnPropertyChanged("增刪修");} }
        public string 選擇 { get{ if (unitbaModel.選擇==null) {unitbaModel.選擇="";}  return unitbaModel.選擇 ;} set{unitbaModel.選擇 = value; 	OnPropertyChanged("選擇");} }
        public int 管制碼 { get{return unitbaModel.管制碼 ;} set{unitbaModel.管制碼 = value;	OnPropertyChanged("管制碼"); } }
        public short srvdbid { get{return unitbaModel.srvdbid ;} set{unitbaModel.srvdbid = value;	OnPropertyChanged("srvdbid"); } }
        public int pkid { get{return unitbaModel.pkid ;} set{unitbaModel.pkid = value;	OnPropertyChanged("pkid"); } }
        public int logid { get{return unitbaModel.logid ;} set{unitbaModel.logid = value;	OnPropertyChanged("logid"); } }
        public int linkid { get{return unitbaModel.linkid ;} set{unitbaModel.linkid = value;	OnPropertyChanged("linkid"); } }
    }
}
