
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
using System.Xml.Serialization;
public partial class accl
{

[XmlAttribute()]
    public string 科目代號 { get; set; }

[XmlAttribute()]
    public string 科目名稱 { get; set; }

[XmlAttribute()]
    public string 英文簡稱 { get; set; }

[XmlAttribute()]
    public string 英文名稱 { get; set; }

[XmlAttribute()]
    public string 借貸別 { get; set; }

[XmlAttribute()]
    public string 輸入傳票 { get; set; }

[XmlAttribute()]
    public string 大分類 { get; set; }

[XmlAttribute()]
    public string 中分類 { get; set; }

[XmlAttribute()]
    public string 小分類 { get; set; }

[XmlAttribute()]
    public string 英文大分類 { get; set; }

[XmlAttribute()]
    public string 英文中分類 { get; set; }

[XmlAttribute()]
    public string 英文小分類 { get; set; }

[XmlAttribute()]
    public string 科目分類 { get; set; }

[XmlAttribute()]
    public string 常用摘要 { get; set; }

[XmlAttribute()]
    public string 是否立沖 { get; set; }

[XmlAttribute()]
    public string 科目性質 { get; set; }

[XmlAttribute()]
    public string 控制方式1 { get; set; }

[XmlAttribute()]
    public string 控制方式2 { get; set; }

[XmlAttribute()]
    public string 控制方式3 { get; set; }

[XmlAttribute()]
    public string 控制方式4 { get; set; }

[XmlAttribute()]
    public string 控制方式5 { get; set; }

[XmlAttribute()]
    public string 控制方式6 { get; set; }

[XmlAttribute()]
    public string 控制方式7 { get; set; }

[XmlAttribute()]
    public string 控制方式8 { get; set; }

[XmlAttribute()]
    public string 控制方式9 { get; set; }

[XmlAttribute()]
    public string 控制方式a { get; set; }

[XmlAttribute()]
    public string 品號抓群組 { get; set; }

[XmlAttribute()]
    public string 項目分類 { get; set; }

[XmlAttribute()]
    public string 關帳日期 { get; set; }

[XmlAttribute()]
    public string 原科目代號 { get; set; }

[XmlAttribute()]
    public string 原科目名稱 { get; set; }

[XmlAttribute()]
    public System.DateTime 輸入日期 { get; set; }

[XmlAttribute()]
    public string 輸入人員 { get; set; }

[XmlAttribute()]
    public string 輸入地點 { get; set; }

[XmlAttribute()]
    public string 增刪修 { get; set; }

[XmlAttribute()]
    public string 選擇 { get; set; }

[XmlAttribute()]
    public int 管制碼 { get; set; }

[XmlAttribute()]
    public short srvdbid { get; set; }

[XmlAttribute()]
    public int pkid { get; set; }

[XmlAttribute()]
    public int logid { get; set; }

[XmlAttribute()]
    public int linkid { get; set; }

}

}
