//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class accl
    {
        public string 科目代號 { get; set; }
        public string 科目名稱 { get; set; }
        public string 英文簡稱 { get; set; }
        public string 英文名稱 { get; set; }
        public string 借貸別 { get; set; }
        public string 輸入傳票 { get; set; }
        public string 大分類 { get; set; }
        public string 中分類 { get; set; }
        public string 小分類 { get; set; }
        public string 英文大分類 { get; set; }
        public string 英文中分類 { get; set; }
        public string 英文小分類 { get; set; }
        public string 科目分類 { get; set; }
        public string 常用摘要 { get; set; }
        public string 是否立沖 { get; set; }
        public string 科目性質 { get; set; }
        public string 控制方式1 { get; set; }
        public string 控制方式2 { get; set; }
        public string 控制方式3 { get; set; }
        public string 控制方式4 { get; set; }
        public string 控制方式5 { get; set; }
        public string 控制方式6 { get; set; }
        public string 控制方式7 { get; set; }
        public string 控制方式8 { get; set; }
        public string 控制方式9 { get; set; }
        public string 控制方式a { get; set; }
        public string 品號抓群組 { get; set; }
        public string 項目分類 { get; set; }
        public string 關帳日期 { get; set; }
        public string 原科目代號 { get; set; }
        public string 原科目名稱 { get; set; }
        public System.DateTime 輸入日期 { get; set; }
        public string 輸入人員 { get; set; }
        public string 輸入地點 { get; set; }
        public string 增刪修 { get; set; }
        public string 選擇 { get; set; }
        public int 管制碼 { get; set; }
        public short srvdbid { get; set; }
        public int pkid { get; set; }
        public int logid { get; set; }
        public Nullable<int> linkid { get; set; }
    }
}
