
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
using System.Xml.Serialization;
public partial class cupdt
{

[XmlAttribute()]
    public string 序號 { get; set; }

[XmlAttribute()]
    public string 客戶品號 { get; set; }

[XmlAttribute()]
    public string 品號 { get; set; }

[XmlAttribute()]
    public string 品名 { get; set; }

[XmlAttribute()]
    public string 單位 { get; set; }

[XmlAttribute()]
    public decimal 數量 { get; set; }

[XmlAttribute()]
    public decimal 標準單價 { get; set; }

[XmlAttribute()]
    public decimal 單價 { get; set; }

[XmlAttribute()]
    public decimal 材料費 { get; set; }

[XmlAttribute()]
    public decimal 加工費 { get; set; }

[XmlAttribute()]
    public decimal 分攤金額 { get; set; }

[XmlAttribute()]
    public int 分攤數量 { get; set; }

[XmlAttribute()]
    public decimal 模具費 { get; set; }

[XmlAttribute()]
    public decimal 建議售價 { get; set; }

[XmlAttribute()]
    public int 最低訂單量 { get; set; }

[XmlAttribute()]
    public int 最低包裝數 { get; set; }

[XmlAttribute()]
    public int leadtime { get; set; }

[XmlAttribute()]
    public decimal 報價成本 { get; set; }

[XmlAttribute()]
    public string 異動日期 { get; set; }

[XmlAttribute()]
    public string 異動原因 { get; set; }

[XmlAttribute()]
    public string 模具編號 { get; set; }

[XmlAttribute()]
    public string 備註 { get; set; }

[XmlAttribute()]
    public decimal 單重 { get; set; }

[XmlAttribute()]
    public System.DateTime 輸入日期 { get; set; }

[XmlAttribute()]
    public string 輸入人員 { get; set; }

[XmlAttribute()]
    public string 輸入地點 { get; set; }

[XmlAttribute()]
    public string 增刪修 { get; set; }

[XmlAttribute()]
    public string 選擇 { get; set; }

[XmlAttribute()]
    public int 管制碼 { get; set; }

[XmlAttribute()]
    public short srvdbid { get; set; }

[XmlAttribute()]
    public int pkid { get; set; }

[XmlAttribute()]
    public int logid { get; set; }

[XmlAttribute()]
    public int linkid { get; set; }

[XmlAttribute()]
    public string 單品報價號 { get; set; }

}

}
