//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.Xml.Serialization;
    public partial class cupdma
    {
    [XmlAttribute()]
        public string 報價單號 { get; set; }
    [XmlAttribute()]
        public string 序號前置碼 { get; set; }
    [XmlAttribute()]
        public short 公司代碼 { get; set; }
    [XmlAttribute()]
        public string 報價別 { get; set; }
    [XmlAttribute()]
        public string 報價人員 { get; set; }
    [XmlAttribute()]
        public string 客戶代號 { get; set; }
    [XmlAttribute()]
        public string 客戶名稱 { get; set; }
    [XmlAttribute()]
        public string 報價日期 { get; set; }
    [XmlAttribute()]
        public string 幣別 { get; set; }
    [XmlAttribute()]
        public decimal 匯率 { get; set; }
    [XmlAttribute()]
        public string 聯絡人 { get; set; }
    [XmlAttribute()]
        public string 傳真 { get; set; }
    [XmlAttribute()]
        public string 電話 { get; set; }
    [XmlAttribute()]
        public decimal 最低毛利率 { get; set; }
    [XmlAttribute()]
        public string 收付條件號 { get; set; }
    [XmlAttribute()]
        public int 有效天數 { get; set; }
    [XmlAttribute()]
        public string 頁首備註 { get; set; }
    [XmlAttribute()]
        public string 報價備註 { get; set; }
    [XmlAttribute()]
        public int 聯絡單id { get; set; }
    [XmlAttribute()]
        public string 工作流程 { get; set; }
    [XmlAttribute()]
        public string 審核人員 { get; set; }
    [XmlAttribute()]
        public string 審核日期 { get; set; }
    [XmlAttribute()]
        public string 已審核 { get; set; }
    [XmlAttribute()]
        public System.DateTime 輸入日期 { get; set; }
    [XmlAttribute()]
        public string 輸入人員 { get; set; }
    [XmlAttribute()]
        public string 輸入地點 { get; set; }
    [XmlAttribute()]
        public string 增刪修 { get; set; }
    [XmlAttribute()]
        public string 選擇 { get; set; }
    [XmlAttribute()]
        public int 管制碼 { get; set; }
    [XmlAttribute()]
        public short srvdbid { get; set; }
    [XmlAttribute()]
        public int pkid { get; set; }
    [XmlAttribute()]
        public int logid { get; set; }
    [XmlAttribute()]
        public int linkid { get; set; }
    }
}
