//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    public partial class DeptModel : INotifyPropertyChanged 
    {
        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(string propertyname)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyname));
            }
        }
        [XmlAttribute()]
        public string 部門代號 { get{ return _部門代號; } set{ _部門代號=value;	OnPropertyChanged("部門代號");} }
    	private string _部門代號 ;
        [XmlAttribute()]
        public string 部門簡稱 { get{ return _部門簡稱; } set{ _部門簡稱=value;	OnPropertyChanged("部門簡稱");} }
    	private string _部門簡稱 ;
        [XmlAttribute()]
        public string 部門名稱 { get{ return _部門名稱; } set{ _部門名稱=value;	OnPropertyChanged("部門名稱");} }
    	private string _部門名稱 ;
        [XmlAttribute()]
        public string 負責主管 { get{ return _負責主管; } set{ _負責主管=value;	OnPropertyChanged("負責主管");} }
    	private string _負責主管 ;
        [XmlAttribute()]
        public string 職稱 { get{ return _職稱; } set{ _職稱=value;	OnPropertyChanged("職稱");} }
    	private string _職稱 ;
        [XmlAttribute()]
        public int 要員人數 { get{ return _要員人數; } set{ _要員人數=value;	OnPropertyChanged("要員人數");} }
    	private int _要員人數 ;
        [XmlAttribute()]
        public string 生產順序 { get{ return _生產順序; } set{ _生產順序=value;	OnPropertyChanged("生產順序");} }
    	private string _生產順序 ;
        [XmlAttribute()]
        public string 製程別 { get{ return _製程別; } set{ _製程別=value;	OnPropertyChanged("製程別");} }
    	private string _製程別 ;
        [XmlAttribute()]
        public string 隸屬倉庫 { get{ return _隸屬倉庫; } set{ _隸屬倉庫=value;	OnPropertyChanged("隸屬倉庫");} }
    	private string _隸屬倉庫 ;
        [XmlAttribute()]
        public string 可用倉庫 { get{ return _可用倉庫; } set{ _可用倉庫=value;	OnPropertyChanged("可用倉庫");} }
    	private string _可用倉庫 ;
        [XmlAttribute()]
        public string 在製倉庫 { get{ return _在製倉庫; } set{ _在製倉庫=value;	OnPropertyChanged("在製倉庫");} }
    	private string _在製倉庫 ;
        [XmlAttribute()]
        public string 出貨倉庫 { get{ return _出貨倉庫; } set{ _出貨倉庫=value;	OnPropertyChanged("出貨倉庫");} }
    	private string _出貨倉庫 ;
        [XmlAttribute()]
        public string 外調倉庫 { get{ return _外調倉庫; } set{ _外調倉庫=value;	OnPropertyChanged("外調倉庫");} }
    	private string _外調倉庫 ;
        [XmlAttribute()]
        public System.DateTime 輸入日期 { get{ return _輸入日期; } set{ _輸入日期=value;	OnPropertyChanged("輸入日期");} }
    	private System.DateTime _輸入日期 ;
        [XmlAttribute()]
        public string 輸入人員 { get{ return _輸入人員; } set{ _輸入人員=value;	OnPropertyChanged("輸入人員");} }
    	private string _輸入人員 ;
        [XmlAttribute()]
        public string 輸入地點 { get{ return _輸入地點; } set{ _輸入地點=value;	OnPropertyChanged("輸入地點");} }
    	private string _輸入地點 ;
        [XmlAttribute()]
        public string 增刪修 { get{ return _增刪修; } set{ _增刪修=value;	OnPropertyChanged("增刪修");} }
    	private string _增刪修 ;
        [XmlAttribute()]
        public string 選擇 { get{ return _選擇; } set{ _選擇=value;	OnPropertyChanged("選擇");} }
    	private string _選擇 ;
        [XmlAttribute()]
        public int 管制碼 { get{ return _管制碼; } set{ _管制碼=value;	OnPropertyChanged("管制碼");} }
    	private int _管制碼 ;
        [XmlAttribute()]
        public short srvdbid { get{ return _srvdbid; } set{ _srvdbid=value;	OnPropertyChanged("srvdbid");} }
    	private short _srvdbid ;
        [XmlAttribute()]
        public int pkid { get{ return _pkid; } set{ _pkid=value;	OnPropertyChanged("pkid");} }
    	private int _pkid ;
        [XmlAttribute()]
        public int logid { get{ return _logid; } set{ _logid=value;	OnPropertyChanged("logid");} }
    	private int _logid ;
        [XmlAttribute()]
        public int linkid { get{ return _linkid; } set{ _linkid=value;	OnPropertyChanged("linkid");} }
    	private int _linkid ;
    }
}
