
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
using System.Xml.Serialization;
public partial class ordetl
{

[XmlAttribute()]
    public string 序號 { get; set; }

[XmlAttribute()]
    public string 出貨別 { get; set; }

[XmlAttribute()]
    public string 客戶品號 { get; set; }

[XmlAttribute()]
    public string 品號 { get; set; }

[XmlAttribute()]
    public string 顏色 { get; set; }

[XmlAttribute()]
    public decimal 數量 { get; set; }

[XmlAttribute()]
    public string 單位 { get; set; }

[XmlAttribute()]
    public decimal 單價 { get; set; }

[XmlAttribute()]
    public decimal 原幣未稅 { get; set; }

[XmlAttribute()]
    public decimal 本幣未稅 { get; set; }

[XmlAttribute()]
    public decimal 含稅單價 { get; set; }

[XmlAttribute()]
    public decimal 原幣含稅 { get; set; }

[XmlAttribute()]
    public decimal 本幣含稅 { get; set; }

[XmlAttribute()]
    public string 預訂交期 { get; set; }

[XmlAttribute()]
    public string 回覆日期 { get; set; }

[XmlAttribute()]
    public decimal 已交數量 { get; set; }

[XmlAttribute()]
    public decimal 請購數量 { get; set; }

[XmlAttribute()]
    public decimal 出通單數量 { get; set; }

[XmlAttribute()]
    public string 是否採購 { get; set; }

[XmlAttribute()]
    public string 是否核發 { get; set; }

[XmlAttribute()]
    public string 製程別 { get; set; }

[XmlAttribute()]
    public string 採購別 { get; set; }

[XmlAttribute()]
    public string 備註 { get; set; }

[XmlAttribute()]
    public string 備註1 { get; set; }

[XmlAttribute()]
    public string 產品備註 { get; set; }

[XmlAttribute()]
    public string 廠商代號 { get; set; }

[XmlAttribute()]
    public decimal 建議採購量 { get; set; }

[XmlAttribute()]
    public string 建議交期 { get; set; }

[XmlAttribute()]
    public decimal 建議售價 { get; set; }

[XmlAttribute()]
    public string 是否結案 { get; set; }

[XmlAttribute()]
    public string 製通單號 { get; set; }

[XmlAttribute()]
    public int 包裝量 { get; set; }

[XmlAttribute()]
    public int 標籤數 { get; set; }

[XmlAttribute()]
    public string 交貨地點 { get; set; }

[XmlAttribute()]
    public string 客戶訂單號 { get; set; }

[XmlAttribute()]
    public string reqno { get; set; }

[XmlAttribute()]
    public string 合併單號 { get; set; }

[XmlAttribute()]
    public string 結關日期 { get; set; }

[XmlAttribute()]
    public string 分批交貨 { get; set; }

[XmlAttribute()]
    public string 交期變更 { get; set; }

[XmlAttribute()]
    public string 客戶交期 { get; set; }

[XmlAttribute()]
    public decimal 補貨數量 { get; set; }

[XmlAttribute()]
    public string 客訂單序號 { get; set; }

[XmlAttribute()]
    public string 營業確認 { get; set; }

[XmlAttribute()]
    public string 訂單分類 { get; set; }

[XmlAttribute()]
    public string 原品號 { get; set; }

[XmlAttribute()]
    public decimal 原數量 { get; set; }

[XmlAttribute()]
    public string 原單位 { get; set; }

[XmlAttribute()]
    public string 修改註記 { get; set; }

[XmlAttribute()]
    public string 原預訂交期 { get; set; }

[XmlAttribute()]
    public string 生產回覆者 { get; set; }

[XmlAttribute()]
    public string 生回覆日期 { get; set; }

[XmlAttribute()]
    public string 生回覆地點 { get; set; }

[XmlAttribute()]
    public string 初建日期 { get; set; }

[XmlAttribute()]
    public string 初建時間 { get; set; }

[XmlAttribute()]
    public string 初回日期 { get; set; }

[XmlAttribute()]
    public string 初回時間 { get; set; }

[XmlAttribute()]
    public string 業務員編號 { get; set; }

[XmlAttribute()]
    public byte 訂單類別碼 { get; set; }

[XmlAttribute()]
    public System.DateTime 輸入日期 { get; set; }

[XmlAttribute()]
    public string 輸入人員 { get; set; }

[XmlAttribute()]
    public string 輸入地點 { get; set; }

[XmlAttribute()]
    public string 增刪修 { get; set; }

[XmlAttribute()]
    public string 選擇 { get; set; }

[XmlAttribute()]
    public int 管制碼 { get; set; }

[XmlAttribute()]
    public short srvdbid { get; set; }

[XmlAttribute()]
    public int pkid { get; set; }

[XmlAttribute()]
    public int logid { get; set; }

[XmlAttribute()]
    public int linkid { get; set; }

}

}
