//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.Xml.Serialization;
    public partial class salesmen
    {
    [XmlAttribute()]
        public string 業務員編號 { get; set; }
    [XmlAttribute()]
        public string 姓名 { get; set; }
    [XmlAttribute()]
        public string 部門代號 { get; set; }
    [XmlAttribute()]
        public string 到職日期 { get; set; }
    [XmlAttribute()]
        public string 離職日期 { get; set; }
    [XmlAttribute()]
        public System.DateTime 輸入日期 { get; set; }
    [XmlAttribute()]
        public string 輸入人員 { get; set; }
    [XmlAttribute()]
        public string 輸入地點 { get; set; }
    [XmlAttribute()]
        public string 增刪修 { get; set; }
    [XmlAttribute()]
        public string 選擇 { get; set; }
    [XmlAttribute()]
        public int 管制碼 { get; set; }
    [XmlAttribute()]
        public short srvdbid { get; set; }
    [XmlAttribute()]
        public int pkid { get; set; }
    [XmlAttribute()]
        public int logid { get; set; }
    [XmlAttribute()]
        public int linkid { get; set; }
    }
}
