//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sliy
    {
        public string 序號 { get; set; }
        public string 科目代號 { get; set; }
        public string 幣別 { get; set; }
        public decimal 原借方金額 { get; set; }
        public decimal 原貸方金額 { get; set; }
        public decimal 匯率 { get; set; }
        public decimal 本借方金額 { get; set; }
        public decimal 本貸方金額 { get; set; }
        public decimal 功能幣匯率 { get; set; }
        public decimal 借方金額 { get; set; }
        public decimal 貸方金額 { get; set; }
        public decimal 集團幣匯率 { get; set; }
        public decimal 集借方金額 { get; set; }
        public decimal 集貸方金額 { get; set; }
        public string 摘要 { get; set; }
        public string 分類索引1 { get; set; }
        public string 分類索引2 { get; set; }
        public string 分類索引3 { get; set; }
        public string 項目編號 { get; set; }
        public string 部門代號 { get; set; }
        public string 客廠代號 { get; set; }
        public string 員工編號 { get; set; }
        public string 專案代號 { get; set; }
        public string 產品群組 { get; set; }
        public string 單別1 { get; set; }
        public string 單號1 { get; set; }
        public string 單別2 { get; set; }
        public string 單號2 { get; set; }
        public int 財務單id { get; set; }
        public int 財務明細id { get; set; }
        public string 品號 { get; set; }
        public decimal 數量 { get; set; }
        public string 單位 { get; set; }
        public decimal 單價 { get; set; }
        public decimal 折扣 { get; set; }
        public decimal 金額 { get; set; }
        public string 收付款日 { get; set; }
        public string 到期日 { get; set; }
        public System.DateTime 輸入日期 { get; set; }
        public string 輸入人員 { get; set; }
        public string 輸入地點 { get; set; }
        public string 增刪修 { get; set; }
        public string 選擇 { get; set; }
        public int 管制碼 { get; set; }
        public short srvdbid { get; set; }
        public int pkid { get; set; }
        public int logid { get; set; }
        public Nullable<int> linkid { get; set; }
    }
}
