//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sliym
    {
        public short 公司代碼 { get; set; }
        public string 帳別 { get; set; }
        public string 傳票號碼 { get; set; }
        public string 傳票日期 { get; set; }
        public string 傳票種類 { get; set; }
        public decimal 功能幣匯率 { get; set; }
        public decimal 集團幣匯率 { get; set; }
        public string 專案代號a { get; set; }
        public string 是否過帳 { get; set; }
        public string 轉入類別 { get; set; }
        public string 轉入備註 { get; set; }
        public string 過帳備註 { get; set; }
        public string 內外關連號 { get; set; }
        public string 關係人傳票 { get; set; }
        public int 聯絡單id { get; set; }
        public string 工作流程 { get; set; }
        public string 審核人員 { get; set; }
        public string 審核日期 { get; set; }
        public string 已審核 { get; set; }
        public System.DateTime 輸入日期 { get; set; }
        public string 輸入人員 { get; set; }
        public string 輸入地點 { get; set; }
        public string 增刪修 { get; set; }
        public string 選擇 { get; set; }
        public int 管制碼 { get; set; }
        public short srvdbid { get; set; }
        public int pkid { get; set; }
        public int logid { get; set; }
        public Nullable<int> linkid { get; set; }
    }
}
