//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    public partial class UnitbaModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(string propertyname)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyname));
            }
        }       
        [XmlAttribute()]
        public string 單位 { get{ return _單位; } set{ _單位=value;	OnPropertyChanged("單位");} }
    	private string _單位 ;
        [XmlAttribute()]
        public string 說明 { get{ return _說明; } set{ _說明=value;	OnPropertyChanged("說明");} }
    	private string _說明 ;
        [XmlAttribute()]
        public byte 小數位數 { get{ return _小數位數; } set{ _小數位數=value;	OnPropertyChanged("小數位數");} }
    	private byte _小數位數 ;
        [XmlAttribute()]
        public System.DateTime 輸入日期 { get{ return _輸入日期; } set{ _輸入日期=value;	OnPropertyChanged("輸入日期");} }
    	private System.DateTime _輸入日期 ;
        [XmlAttribute()]
        public string 輸入人員 { get{ return _輸入人員; } set{ _輸入人員=value;	OnPropertyChanged("輸入人員");} }
    	private string _輸入人員 ;
        [XmlAttribute()]
        public string 輸入地點 { get{ return _輸入地點; } set{ _輸入地點=value;	OnPropertyChanged("輸入地點");} }
    	private string _輸入地點 ;
        [XmlAttribute()]
        public string 增刪修 { get{ return _增刪修; } set{ _增刪修=value;	OnPropertyChanged("增刪修");} }
    	private string _增刪修 ;
        [XmlAttribute()]
        public string 選擇 { get{ return _選擇; } set{ _選擇=value;	OnPropertyChanged("選擇");} }
    	private string _選擇 ;
        [XmlAttribute()]
        public int 管制碼 { get{ return _管制碼; } set{ _管制碼=value;	OnPropertyChanged("管制碼");} }
    	private int _管制碼 ;
        [XmlAttribute()]
        public short srvdbid { get{ return _srvdbid; } set{ _srvdbid=value;	OnPropertyChanged("srvdbid");} }
    	private short _srvdbid ;
        [XmlAttribute()]
        public int pkid { get{ return _pkid; } set{ _pkid=value;	OnPropertyChanged("pkid");} }
    	private int _pkid ;
        [XmlAttribute()]
        public int logid { get{ return _logid; } set{ _logid=value;	OnPropertyChanged("logid");} }
    	private int _logid ;
        [XmlAttribute()]
        public int linkid { get{ return _linkid; } set{ _linkid=value;	OnPropertyChanged("linkid");} }
    	private int _linkid ;
    }
}
