using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace DarbWareERP.控制項
{
    /// <summary>
    /// DataGrid.xaml 的互動邏輯
    /// </summary>
    public partial class tsDataGrid : DataGrid
    {
        public tsDataGrid()
        {
            InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            欄位格式設定 window = new 欄位格式設定(this, this.Tag.ToString());
            window.ShowDialog();
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            欄位格式設定.欄位格式讀取(this, this.Tag.ToString());
        }
    }
}
