using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.IO;

namespace DarbWareERP.控制項
{
    /// <summary>
    /// DataGrid.xaml 的互動邏輯
    /// </summary>
    public partial class 導覽區DataGrid : UserControl
    {
        
        public 導覽區DataGrid()
        {
            InitializeComponent();
        }
        

        private void button1_Click(object sender, RoutedEventArgs e)
        {
            欄位格式設定 window = new 欄位格式設定(dataGrid, this.Tag.ToString() + "導覽區");
            window.ShowDialog();
        }

        private void dataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
           欄位格式設定.欄位格式讀取(dataGrid, this.Tag.ToString() + "導覽區");
        }
    }
}
